### ISSUE TITLE
Can no longer install/update extension

### ISSUE THREAD

**Issue by zolrath** [blakedietz/vscode-snippets-liveview#1]
Hello!

When attempting to install or update this extension, either from the marketplace or by downloading the vsix, I am now greeted with this error:

```
ENOENT: no such file or directory, open 'c:\Users\furd\.vscode\extensions\.6e96327d-4264-4341-b6bb-8b65e8a398b5\lib\priv\snippets\phoenix_component_changed?'
```

resulting in the extension failing to install. This is with the latest version of the plugin and VS Code 1.76.2 on Windows 11.

My guess is it's the `?` in the filename as it's a restricted character on Windows.

Thanks for the extension!

**Comment by blakedietz** [comment]
Apologies for the miss on this. I'll be taking a look now.
