### ISSUE TITLE
Tag based snippets are available in non tag based contexts

### ISSUE THREAD

**Issue by blakedietz** [blakedietz/vscode-snippets-liveview#7]
I merged this without realizing that this also breaks usages of tag based snippets in `~H` sigils. 

https://github.com/blakedietz/vscode-snippets-liveview/pull/6

I ended up reverting the changes [here](https://github.com/blakedietz/vscode-snippets-liveview/commit/af09bb65fe6d05fc41e6941799e48c6c041fe000).

Will need to do more investigation on how to properly scope down these snippets to the right contexts.

**Comment by blakedietz** [comment]
@aifrak heads up as to why #6 might not be possible unless you have a better solution. I'm all ears. I'll investigate further for alternatives.

**Comment by aifrak** [comment]
@blakedietz Sorry for this mistake.

The suggestion pollution mentioned in PR #6 does not happen in PR #8. So I think the best solution is actually in #8.

**Comment by blakedietz** [comment]
Oh nice! Okay then. Getting that merged then released then off to merge your latest pr in.
